### PR TITLE
Migrate tesseract_rosutils, tesseract_plugins, and most of tesseract_monitoring to ROS 2

### PR DESCRIPTION
**Pull request by schornakj**
Most of the changes are just updates to message names, publishers, subscribers, and services. ~~The potentially-big structural change is that the environment monitor in tesseract_monitoring always contains a ROS node, which simplifies parameter lookups and topic subscriptions from within the monitor.~~ I was able to implement the environment monitor in an equivalent manner to the current ROS1 version.

I haven't migrated the examples and test cases yet, so these packages may change in the future if it turns out that something needs to be different to work in an actual planning application.

### CODE REVIEW

**Comment by schornakj** [comment]
Force-push is to make the diff reflect actual changes vs. the original ROS packages.

**Comment by schornakj** [comment]
The environment monitor can now be either run as a standalone node or instantiated as a member of a different node.

**Comment by Levi-Armstrong** [comment]
@schornakj I gave you write access to repository. I recommend reviewing the latest changes to tesseract_ros which I believe we have made some bug fixes that should probably be captured. I recommend have @ben-greenberg  review this.

**Comment by mpowelson** [comment]
What is the status of this pull request? Is it up to date with the latest changes that have been made? Is there anything I can do to help? @schornakj @marrts @Levi-Armstrong

**Comment by marrts** [comment]
It needs to be updated to reflect the newest tesseract changes.

**Comment by schornakj** [comment]
I  cherry-picked [the last commit](https://github.com/ben-greenberg/tesseract_ros2/commits/feature/continuous_collision_improvements) from @ben-greenberg and @marrts  's branch, which fixes the compatibility issues with the newest version of Tesseract. @Levi-Armstrong suggested checking against the current ROS1 versions of these packages to make sure that all the bugfixes and functional changes have been merged in, so if you (@mpowelson) have time to do that that would be very helpful.

The current version of the `tesseract_ros2` master is really out-of-date and essentially nonfunctional so I was considering merging in this PR in its current state and fixing any remaining issues with new PRs. Any thoughts/objections?

**Pull request merged**
